### ISSUE TITLE
Distribute webserver_controller.go source code into multiple files

### ISSUE THREAD

**Issue by pitprok** [web-servers/jws-operator#39]
I believe that the code in webserver_controller.go could be more easily maintained if we figured out a way to split it into separate .go files and used imports to bring the methods back into webserver_controller.go.
One way to do it would be to break it into 3 parts, Kubernetes-only logic, Openshift-only logic, and general use methods.
@jfclere Let me know what you think.

**Comment by jfclere** [comment]
+1 I will look to it now.

**Comment by pitprok** [comment]
https://github.com/web-servers/jws-operator/commit/af5c0b56f42af84d44440c45cf8fe8f1b1957649
