### ISSUE TITLE
migrate to 1.x version of the operator-skd

### ISSUE THREAD

**Issue by jfclere** [web-servers/jws-operator#42]
See https://sdk.operatorframework.io/docs/building-operators/golang/migration/

**Comment by pitprok** [comment]
@jfclere I see that we're at 0.18.2, which means the version has to be changed again. What is the target version ?

**Comment by jfclere** [comment]
@pitprok the goal is to move to the 1.x SDK ASAP but that is some work.

**Comment by jfclere** [comment]
Done
